name: push-to-s3

on:
  repository_dispatch:
    types: [trigger-from-dev-docs]

jobs:
  push-to-s3:
    name: "Push Hugo Site To S3"
    runs-on: ubuntu-latest
    steps:
      - name: "Push Hugo Site To S3"
        shell: bash
        run: echo "Hello World"

