name: push-to-s3

on:
  workflow_dispatch:

jobs:
  push-to-s3:
    name: "Push Hugo Site To S3"
    runs-on: ubuntu-latest
    steps:
      - name: "Push Hugo Site To S3"
        shell: bash
        run: echo "Hello World"

